name: test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows  Setup
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Cloudflared
      run: |
        Invoke-WebRequest -Uri https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
        .\cloudflared.exe --version

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 1

    - name: Set RDP Password
      run: |
        $Password = ${{ secrets.RDP_PASSWORD }}
        # 验证密码复杂性
        if ($Password.Length -lt 12 -or 
            -not ($Password -match '[A-Z]') -or 
            -not ($Password -match '[a-z]') -or 
            -not ($Password -match '\d') -or 
            -not ($Password -match '[^A-Za-z0-9]')) {
            Write-Error "密码必须至少包含12个字符，并包含大小写字母、数字和特殊字符"
            exit 1
        }
        $SecurePassword = ConvertTo-SecureString $Password -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $SecurePassword
        Write-Host "RDP 密码已设置完成"

    - name: Start Cloudflare Tunnel
      run: |
        .\cloudflared.exe service install ${{ secrets.TUNNEL_TOKEN }}
        Start-Service cloudflared
        Write-Host "Cloudflare Tunnel 服务已启动"

    - name: Keep Alive
      run: |
        Write-Host "远程桌面连接信息："
        Write-Host "用户名: runneradmin"
        Write-Host "密码: 请使用在GitHub Secrets中设置的RDP_PASSWORD"
        Write-Host "保持连接活跃中..."
        while($true) { Start-Sleep -Seconds 60 }